man1_pages = [
  'tulpar.1',
  'tulpar-install.1',
  'tulpar-remove.1',
  'tulpar-upgrade.1',
  'tulpar-search.1',
  'tulpar-list.1',
  'tulpar-info.1',
  'tulpar-verify.1',
  'tulpar-orphans.1',
  'tulpar-hold.1',
  'tulpar-unhold.1',
  'tulpar-history.1',
  'tulpar-repo.1',
  'tulpar-download.1',
  'tulpar-key.1',
]

install_man(man1_pages)
install_man('tulpar.conf.5')
